* eglot instead of lsp-mode?
https://github.com/joaotavora/eglot
** Feature comparison
   - lsp-mode features: https://emacs-lsp.github.io/lsp-mode/
   - eglot features: https://www.gnu.org/software/emacs/manual/html_node/eglot/Eglot-Features.html#Eglot-Features
   According to reddit dwellers, lsp-mode has more features, but eglot just works and it supports the main features anyways.


* React tutorial in emacs
Don't know how good it may be, but I could check it out: https://emacs-lsp.github.io/lsp-mode/tutorials/reactjs-tutorial/


* Build a config for golang
Will need it for portal-api.
Somewhere to start: https://arnesonium.com/2023/08/configuring-emacs-29-1-for-golang


* DONE Treesitter: how to use it?
ANSWER: via a lib. Emacs enables tree-sitter (which is used by many editors), and a lib uses it. Emacs has `combobulate`. I reviewed it and think the best I'll get is navigation.

Seems to be a new way to navigate code.
Shoud test this guide, although it might be a bit outdated: https://www.masteringemacs.org/article/how-to-get-started-tree-sitter
Double down on Emacs and get the damn book? https://www.masteringemacs.org/ (might lead to more, rather than less study time)

** Initial actions taken
*** DONE Install language support
Make sure installation is automatic. Config should be in a single file (ideally .emacs.base.el).
See `(setq treesit-language-source-alist...` in https://www.masteringemacs.org/article/how-to-get-started-tree-sitter
**** GOOD: Configuring the sources in .emacs.base.el works
**** BAD: need to run `M-x treesit-install-language-grammar` once before the language files are available to emacs.
**** Alternative would be to use `add-to-list` to spread the language sources between the configs (and, therefore, between the envs)
*** DONE Remove rust lang reference from the rust config
Now that the language sources are specified in the base config, remove it from .emacs.rust.el
*** DONE Update the docs in base config

** treesite-explore-mode seems to run (something)...
...but still don't know how to use treesite to effectively navigate. I use `M-h` and `M-S-h` but it's normal mark-paragraph.


* Is it time to finally start using Magit?
treemacs integrates with it.


* DONE Project directory tree navigator
I'm getting used to using it, specially for large projects.
I really like the screenshot in: https://github.com/emacs-lsp/lsp-treemacs (but there's no link or reference to how it's achieved XD)

** I already have treemacs and lsp-treemacs!?
Apparently, I already had a project navigator system. Integrated to LSP, too.
https://github.com/Alexander-Miller/treemacs
https://github.com/emacs-lsp/lsp-treemacs

*** Investigate git-mode
https://github.com/Alexander-Miller/treemacs?tab=readme-ov-file#git-mode
Seems to already be activated
*** Investigate filewatch-mode
https://github.com/Alexander-Miller/treemacs?tab=readme-ov-file#filewatch-mode
Seems to already be activated


** Projectile + Neotree
Cancelled in favor of treemacs.
*** Projectile, learn how to use it
https://github.com/bbatsov/projectile
Adds support for "search across project", which is the find-all-references I want :)
Seems to be the backend and the preferred option. I'm installing it in my react configs, but don't know how to use it.
*** Neotree
https://github.com/jaypei/emacs-neotree
One of several implementations. Supports themes, which (according to the docs) makes it look a lot like the screenshot referenced in [[Project directory tree navigator]].


* Flymake-mode hangs my emacs !?
Noted on 2024-10-01 that `M-x flymake-mode` hangs my emacs session. Why?!
Doesn't hang for all my envs, though (it's not hanging for .emacs.react.el)


* Status of LSP in my configs
** python
*** flycheck doesn't work!?
See barchar/bin/barchar:L85
** rust
*** working fine: flycheck, 


* Fix the symbols in fonts
The bulb and other non-alphanumerical symbols doesn't render. I think this is a system problem :/
